import {SolveResult} from '../types';import {decimalsFrom,fmt} from '../rounding';import {compareSpeeds} from './compare';import {solveRateConversion,solveConversion} from './rate';
const result=(x:Omit<SolveResult,'solved'>):SolveResult=>({solved:true,...x});
export function solve(q:string):SolveResult{const s=q.toLowerCase(),d=decimalsFrom(q);let m;{const c=compareSpeeds(q)||solveRateConversion(q);if(c)return c;}
if((s.includes('millimeter')||s.includes(' mm'))&&s.includes('inch')&&(m=q.match(/(\d+(?:\.\d+)?)\s*inches?/i))){const n=+m[1],v=n*25.4;return result({answer:`${fmt(v,d)} mm`,title:'Inches to Millimeters',category:'Conversion',easyFormula:'Millimeters = inches × millimeters per inch',standardFormula:'mm = in × 25.4',setup:`${n} × 25.4 = ${fmt(v,d)}`,steps:[`Start with ${n} inches.`,'One inch equals 25.4 millimeters.',`Multiply ${n} by 25.4.`,`The result is ${fmt(v,d)} millimeters.`],units:'mm',rounding:d===null?'No special rounding requested':`${d} decimal places`});}
if(s.includes('grams')&&s.includes('pound')){const nums=[...q.matchAll(/(\d+(?:\.\d+)?)\s*grams?/gi)].map(x=>+x[1]).filter(n=>n!==453.592);const per=+(q.match(/(\d+(?:\.\d+)?)\s*grams?\s+in\s+(?:one|1)\s+pound/i)?.[1]||453.592);if(nums.length){const ans=nums.map(n=>`${n} grams = ${fmt(n/per,d??2)} pounds`);return result({answer:ans.join('\n'),answers:ans,title:'Grams to Pounds',category:'Conversion',easyFormula:'Pounds = grams ÷ grams per pound',standardFormula:'lb = g ÷ 453.592',setup:nums.map(n=>`${n} ÷ ${per} = ${fmt(n/per,d??2)}`).join('\n'),steps:nums.map(n=>`Divide ${n} grams by ${per}; result = ${fmt(n/per,d??2)} pounds.`),units:'lb',rounding:`${d??2} decimal places`});}}
if(s.includes('gear ratio')){const a=+(q.match(/(\d+(?:\.\d+)?)\s+teeth[^.]{0,40}front/i)?.[1]||q.match(/front[^.]{0,30}?(\d+(?:\.\d+)?)/i)?.[1]||0),b=+(q.match(/(\d+(?:\.\d+)?)\s+teeth[^.]{0,40}rear/i)?.[1]||q.match(/rear[^.]{0,30}?(\d+(?:\.\d+)?)/i)?.[1]||0);if(a&&b){const r=a/b;return result({answer:`${fmt(r)}:1`,title:'Gear Ratio',category:'Ratio / Rate',easyFormula:'Gear ratio = front sprocket teeth ÷ rear sprocket teeth',standardFormula:'G = F ÷ R',setup:`${a} ÷ ${b} = ${fmt(r)}`,steps:['Take the front sprocket teeth.','Divide by the rear sprocket teeth.',`${a} ÷ ${b} = ${fmt(r)}.`,`Write the ratio as ${fmt(r)}:1.`]});}}
if(s.includes('average')||s.includes('mean')){const nums=[...q.matchAll(/\d+(?:\.\d+)?/g)].map(x=>+x[0]);if(nums.length>=2){const v=nums.reduce((a,b)=>a+b,0)/nums.length;return result({answer:fmt(v,d),title:'Arithmetic Mean',category:'Statistics',easyFormula:'Average = add all the numbers ÷ how many numbers there are',standardFormula:'x̄ = Σx ÷ n',setup:`(${nums.join(' + ')}) ÷ ${nums.length} = ${fmt(v,d)}`,steps:[`Add the values: ${fmt(nums.reduce((a,b)=>a+b,0))}.`,`There are ${nums.length} values.`,`Divide the total by ${nums.length}.`],rounding:d===null?'No special rounding requested':`${d} decimal places`});}}
if((s.includes('rectangular')||s.includes('rectangle'))&&s.includes('area')){const l=+(q.match(/length\s+(?:is\s+)?(\d+(?:\.\d+)?)/i)?.[1]||0),w=+(q.match(/width\s+(?:is\s+)?(\d+(?:\.\d+)?)/i)?.[1]||0);if(l&&w){const v=l*w;return result({answer:`${fmt(v,d)} square meters`,title:'Rectangle Area',category:'Geometry',easyFormula:'Area = length × width',standardFormula:'A = l × w',setup:`${l} × ${w} = ${fmt(v,d)}`,steps:[`Use length ${l} and width ${w}.`,`Multiply length by width.`,`Area = ${fmt(v,d)} square meters.`],units:'m²'});}}
if(s.includes('cups')&&s.includes('minute')&&s.includes('gallon')&&s.includes('hour')){const rate=+(q.match(/(\d+(?:\.\d+)?)\s*cups?[^.]*per minute/i)?.[1]||0),hours=+(q.match(/(\d+(?:\.\d+)?)\s*hours?/i)?.[1]||0),cpg=+(q.match(/(\d+(?:\.\d+)?)\s*cups?\s+in\s+(?:one|1)\s+gallon/i)?.[1]||16);if(rate&&hours){const min=hours*60,cups=rate*min,g=cups/cpg;return result({answer:`${fmt(g,d)} gallons`,title:'Rate and Volume Conversion',category:'Rate / Conversion',easyFormula:'Gallons = cups per minute × minutes ÷ cups per gallon',standardFormula:'gal = (cup/min × min) ÷ (cup/gal)',setup:`${hours} × 60 = ${min} min; ${rate} × ${min} = ${cups} cups; ${cups} ÷ ${cpg} = ${fmt(g,d)} gal`,steps:[`${hours} hours × 60 = ${min} minutes.`,`${rate} cups/min × ${min} = ${cups} cups.`,`${cups} ÷ ${cpg} = ${fmt(g,d)} gallons.`],units:'gal'});}}
{const c=solveConversion(q);if(c)return c;}
return {solved:false,answer:'Not enough information to solve this deterministically.',title:'No deterministic solution found',category:'Formula search fallback',easyFormula:'Try adding the quantities, units, and what you need to find.',setup:'',steps:['Check that all required values are included.','Try searching the formula library for the topic.']};}
